import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { SymbolWeight, SymbolViewProps } from "expo-symbols";
import { ComponentProps } from "react";
import { OpaqueColorValue, type StyleProp, type TextStyle } from "react-native";

type IconMapping = Record<SymbolViewProps["name"], ComponentProps<typeof MaterialIcons>["name"]>;
type IconSymbolName = keyof typeof MAPPING;

const MAPPING = {
  // Navigation
  "house.fill": "home",
  "chevron.left": "chevron-left",
  "chevron.right": "chevron-right",
  "chevron.down": "expand-more",
  "chevron.up": "expand-less",
  "xmark": "close",
  "xmark.circle.fill": "cancel",
  "arrow.clockwise": "refresh",
  "arrow.right": "arrow-forward",
  "arrow.left": "arrow-back",
  "arrow.left.arrow.right": "compare-arrows",
  "arrow.up.arrow.down": "swap-vert",
  "arrow.up.right.square": "open-in-new",
  // Actions
  "checkmark": "check",
  "checkmark.circle.fill": "check-circle",
  "checkmark.circle": "check-circle-outline",
  "magnifyingglass": "search",
  "plus": "add",
  "plus.circle.fill": "add-circle",
  "minus.circle.fill": "remove-circle",
  "trash.fill": "delete",
  "pencil": "edit",
  "square.and.arrow.up": "share",
  "doc.fill": "description",
  "doc.text.fill": "article",
  "camera.fill": "camera-alt",
  "photo.fill": "photo",
  "bell.fill": "notifications",
  "bell.badge.fill": "notifications-active",
  "gear": "settings",
  "slider.horizontal.3": "tune",
  "bookmark": "bookmark-border",
  "bookmark.fill": "bookmark",
  "heart": "favorite-border",
  "heart.fill": "favorite",
  "info.circle": "info",
  "info.circle.fill": "info",
  "questionmark.circle.fill": "help",
  "ellipsis": "more-horiz",
  "ellipsis.circle": "more-horiz",
  // Status
  "star.fill": "star",
  "star": "star-border",
  "star.leadinghalf.filled": "star-half",
  "trophy.fill": "emoji-events",
  "medal.fill": "military-tech",
  "sparkles": "auto-awesome",
  "exclamationmark.triangle.fill": "warning",
  "exclamationmark.circle.fill": "error",
  "checkmark.seal.fill": "verified",
  "lock.fill": "lock",
  "lock.open.fill": "lock-open",
  // Health & Medical
  "pills.fill": "medication",
  "cross.fill": "add",
  "cross.case.fill": "medical-services",
  "stethoscope": "stethoscope",
  "heart.text.square.fill": "monitor-heart",
  "waveform.path.ecg": "monitor-heart",
  "bandage.fill": "healing",
  "syringe.fill": "vaccines",
  "flask.fill": "science",
  "testtube.2": "biotech",
  "chart.bar.fill": "bar-chart",
  "chart.line.uptrend.xyaxis": "trending-up",
  "chart.pie.fill": "pie-chart",
  // Body & Organs
  "brain.head.profile": "psychology",
  "figure.walk": "directions-walk",
  "figure.run": "directions-run",
  "figure.strengthtraining.traditional": "fitness-center",
  "figure.mind.and.body": "self-improvement",
  "lungs.fill": "air",
  // Nature & Food
  "leaf.fill": "eco",
  "drop.fill": "water-drop",
  "flame.fill": "local-fire-department",
  "sun.max.fill": "wb-sunny",
  "moon.fill": "bedtime",
  "bolt.fill": "bolt",
  "shield.fill": "shield",
  "shield.checkmark.fill": "verified-user",
  "atom": "atom",
  // Education & Content
  "graduationcap.fill": "school",
  "book.fill": "menu-book",
  "book.closed.fill": "import-contacts",
  "newspaper.fill": "newspaper",
  "list.bullet": "list",
  "list.bullet.clipboard.fill": "assignment",
  "checklist": "checklist",
  "text.alignright": "format-align-right",
  "tag.fill": "label",
  // Communication
  "paperplane.fill": "send",
  "bubble.left.fill": "chat-bubble",
  "bubble.left.and.bubble.right.fill": "forum",
  "person.fill": "person",
  "person.2.fill": "group",
  "person.crop.circle.fill": "account-circle",
  "person.crop.circle.badge.plus": "person-add",
  // Time & Calendar
  "clock.fill": "schedule",
  "clock.arrow.circlepath": "history",
  "calendar": "calendar-today",
  "calendar.badge.plus": "event",
  "alarm.fill": "alarm",
  // Misc
  "filter": "filter-list",
  "arrow.3.trianglepath": "recycling",
  "chevron.left.forwardslash.chevron.right": "code",
  "dna": "biotech",
  "pills": "medication-liquid",
  "wand.and.stars": "auto-fix-high",
  "cpu.fill": "memory",
  "network": "hub",
  "map.fill": "map",
  "location.fill": "location-on",
  "building.2.fill": "business",
  "cart.fill": "shopping-cart",
  "creditcard.fill": "credit-card",
  "dollarsign.circle.fill": "monetization-on",
  "percent": "percent",
  "number": "tag",
  "textformat": "text-fields",
  "square.grid.2x2.fill": "grid-view",
  "rectangle.grid.1x2.fill": "view-agenda",
  "line.3.horizontal": "menu",
  "sidebar.left": "view-sidebar",
  "arrow.down.circle.fill": "download",
  "arrow.up.circle.fill": "upload",
  "icloud.fill": "cloud",
  "externaldrive.fill": "storage",
  "printer.fill": "print",
  "qrcode": "qr-code",
  "barcode": "barcode-reader",
  "wrench.and.screwdriver.fill": "build",
  "lightbulb.fill": "lightbulb",
  "lightbulb": "lightbulb-outline",
  "checkmark.square.fill": "check-box",
  "square": "check-box-outline-blank",
  "minus": "remove",
  "plus.square.fill": "add-box",
  "doc.badge.plus": "note-add",
  "arrow.down.to.line": "save-alt",
  "chart.xyaxis.line": "show-chart",
  "waveform": "graphic-eq",
  "person.text.rectangle.fill": "badge",
  "list.number": "format-list-numbered",
  "rectangle.and.pencil.and.ellipsis": "edit-note",
  "text.badge.checkmark": "fact-check",
  "cross.circle.fill": "cancel",
  "drop.degreesign.fill": "thermostat",
  "humidity.fill": "water",
  "wind": "air",
  "allergens": "coronavirus",
  "figure.2": "people",
  "figure.2.arms.open": "people-outline",
  "trophy": "emoji-events",
  "rosette": "workspace-premium",
  "crown.fill": "workspace-premium",
  "flame": "local-fire-department",
  "speedometer": "speed",
  "gauge.medium": "speed",
  "timer": "timer",
  "stopwatch.fill": "timer",
  "bed.double.fill": "hotel",
  "fork.knife": "restaurant",
  "cart": "shopping-cart",
  "bag.fill": "shopping-bag",
  "externaldrive.badge.plus": "add-to-drive",
  "square.and.arrow.down": "download",
  "arrow.uturn.backward": "undo",
  "goforward": "redo",
  "repeat": "repeat",
  "shuffle": "shuffle",
  "play.fill": "play-arrow",
  "pause.fill": "pause",
  "stop.fill": "stop",
  "forward.fill": "fast-forward",
  "backward.fill": "fast-rewind",
  "speaker.wave.3.fill": "volume-up",
  "speaker.slash.fill": "volume-off",
  "mic.fill": "mic",
  "video.fill": "videocam",
  "eye.fill": "visibility",
  "eye.slash.fill": "visibility-off",
  "hand.thumbsup.fill": "thumb-up",
  "hand.thumbsdown.fill": "thumb-down",
  "hand.raised.fill": "back-hand",
  "hands.clap.fill": "front-hand",
  "face.smiling": "sentiment-satisfied",
  "face.dashed": "sentiment-dissatisfied",
  "antenna.radiowaves.left.and.right": "wifi",
  "wifi": "wifi",
  "wifi.slash": "wifi-off",
  "globe": "language",
  "globe.americas.fill": "public",
  "envelope.fill": "email",
  "phone.fill": "phone",
  "flag.fill": "flag",
  "pin.fill": "push-pin",
  "link": "link",
  "scissors": "content-cut",
  "doc.on.doc.fill": "content-copy",
  "paintbrush.fill": "brush",
  "eyedropper": "colorize",
  "slider.vertical.3": "tune",
  "square.stack.fill": "layers",
  "rectangle.stack.fill": "dynamic-feed",
  "tray.fill": "inbox",
  "archivebox.fill": "archive",
  "folder.fill": "folder",
  "folder.badge.plus": "create-new-folder",
} as unknown as IconMapping;

export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name] ?? "help-outline"} style={style} />;
}
